name: PR merge detected

on:
  pull_request:
    types: [closed]

jobs:
  only_if_merged:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR merg√©e !"