name: Push or Pull
on: 
  push:
  pull_request: 
  workflow_dispatch
env:
  MSG_PUSH : "c'est un push ! "
  MSG_PULL: " c'est une pull request ! "
jobs:
  le_push :
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    steps:
      - name: "faire un push"
        run: echo " ${{ env.MSG_PUSH }}"
    
  le_pull_request :
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request'}}
    steps:
      - name: "faire un pull request"
        run: echo " ${{ env.MSG_PULL }}"