name: Pipeline Fruits et Noms

on:
  workflow_dispatch:  # Exécution manuelle

jobs:
  combinaison:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        fruit: [poire, datte, kiwi, orange]
        nom: [Aksil, Gaya, Amir]

    steps:
      - name: Afficher une phrase
        run: echo "${{ matrix.nom }} mange une ${{ matrix.fruit }}, et il adore ça !"
