name: Workflow li√©s

on:
  workflow_dispatch:

jobs:
  job_1:
    name: Job 1 - Lancement manuel
    runs-on: ubuntu-latest

    steps:
      - name: Message du job 1
        run: echo "‚úÖ Le job 1 a √©t√© ex√©cut√© manuellement."

  job_2:
    name: Job 2 - Apr√®s le job 1
    runs-on: ubuntu-latest
    needs: job_1

    steps:
      - name: Message du job 2
        run: echo "üöÄ Le job 2 s'ex√©cute apr√®s le job 1."
