name: Hello World

on: push

jobs:
  hello_word:
    runs-on: ubuntu-latest

    steps:
      # Checkout du dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # Hello World
      - name: Hello World
        run: echo "Hello World"